### ISSUE TITLE
Slax 9 now Debian based instead of Slackware

### ISSUE THREAD

**Issue by ebbi2017** [FabioLolix/LinuxTimeline#101]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
Slax (Version 9)
* Base:
Debian
* Start date:
2017/11
* (eventual) Name changes with date: 

* URL:
https://en.wikipedia.org/wiki/Slax#Slax_9
* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md

**Discontinuing a distribution**

* Name:

* Stop date:

* Statement URL (if any):

**Comment by xingjiapeng** [comment]
https://www.slax.org/

> Slax is now based on Debian, which gives you the ability to benefit from its entire ecosystem. Tens of thousands of prebuilt packages with applications, all within reach thanks to apt command.

I think that's probably right.

**Comment by DestroyerXyz** [comment]
What kind of info do you need?

**Comment by FabioLolix** [comment]
Hello @ebbi2017 and thank you for your patience

I had seen about it in the news

Futher addition to the timeline will be for projects that are at least 2.5 year old, are of quality and have a fullfilled page at my new open archive

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/



> What kind of info do you need?

I want a start date precise to the day

I wasn't able to found sources, public repositories and how to build a Slax iso

I will not add distros that are created with remixing tools

**Comment by ebbi2017** [comment]
Hallo Fabio,

The new Slax 9 iso link is here at the very bottom https://www.slax.org/
Old ones are here, too http://ftp.sh.cvut.cz/slax/
There's no need to master the iso, it's already working OOTB.

Latest Slax 7.0.9 Beta is from 2013_07
http://ftp.sh.cvut.cz/slax/Slax-7.x/
Slax 9 seems to have started in 2017_11, at least these are the oldest iso files of 9.x available (9.2.1 and ipxe are the oldest, there's no 9.0 or 9.1 available...maybe it's because the dev changed from Slackware to Debian, needed some time).
It might have started before, but that's the iso files we can download, 9.2.1+.
http://ftp.sh.cvut.cz/slax/Slax-9.x/

Slax 10.2 testing version based on Debian 10.2 Buster is available here https://www.slax.org/blog.php
Slax 8 never existed.

I only wanted to mention the change between Slax 7 (Slackware) and 9 (Debian), after 4 years of hibernation or silent development.

Cheers

**Comment by FabioLolix** [comment]
@ebbi2017 you're welcome to report any news, issue or information

I guess the new Slax versioning follow the Debian one

>  There's no need to master the iso, it's already working OOTB.

That is not the point, I don't see any source about this distro and how to build it

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template

**Comment by FabioLolix** [comment]
>  There's no need to master the iso, it's already working OOTB.

So have been passed more then 2 years since the last stable release of Slax (on Debian 9), the build on Debian 10 not reached stable status and Debian 11 is the current version, this is a good example of why openess and buildability of a Linux distro matter, you can't relay on remixes like this
