### ISSUE TITLE
add Batocera.linux

### ISSUE THREAD

**Issue by ebbi2017** [FabioLolix/LinuxTimeline#102]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
Batocera.linux
* Base:
RecalBox Remix 4.1 Unstable, since then independent
* Start date:
end of 2017
* (eventual) Name changes with date: 

* URL:
https://batocera.org/ (once was http://batocera-linux.xorhub.com/)
* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md

**Discontinuing a distribution**

* Name:

* Stop date:

* Statement URL (if any):

**Comment by FabioLolix** [comment]
I'm aware of the existence of Batocera (it is in the OS list for Raspberry Pi)

Futher addition to the timeline will be for projects that are at least 2.5 year old, are of quality and have a fullfilled page at my new open archive

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
