### ISSUE TITLE
No redhat root logo

### ISSUE THREAD

**Issue by Andy1978** [FabioLolix/LinuxTimeline#127]
Is there a reason to not use the redhat logo as root like Debian, Slackware and so on?
https://de.wikipedia.org/wiki/Datei:Red_Hat_logo.svg

Perhaps there is some license problem but I haven't found something in the issues. And I would have bet that it was there years ago.

**Comment by FabioLolix** [comment]
https://github.com/FabioLolix/LinuxTimeline/blob/master/images/COPYING

**Comment by DestroyerXyz** [comment]
@FabioLolix I don't understand, you have been given permission in this document or not??

**Comment by DestroyerXyz** [comment]
@Andy1978 You can close this issue if you want as I have made an issue for all missing logos #153

**Comment by FabioLolix** [comment]
Follow on #153
