### ISSUE TITLE
Add postmarketOS

### ISSUE THREAD

**Issue by nicolasmaia** [FabioLolix/LinuxTimeline#128]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name: postmarketOS

* Base: Alpina Linux

* Start date: 2017?

* (eventual) Name changes with date: 

* URL: https://postmarketos.org/

* (optional) Color in hex:

* (optional) Description and history: 

postmarketOS is an experimental, touch-optimized and pre-configured Alpine Linux. It can be installed on smartphones and other devices.

**Discontinuing a distribution**

* Name:

* Stop date:

* Statement URL (if any):

**Comment by FabioLolix** [comment]
Done with #192
