### ISSUE TITLE
Add libreCMC

### ISSUE THREAD

**Issue by nicolasmaia** [FabioLolix/LinuxTimeline#129]
**Adding a distribution**

* Name: libreCMC

* Base: LEDE Project

* Start date: 2014 (see https://en.wikipedia.org/wiki/LibreCMC)

* (eventual) Name changes with date: Not a name change but LibreWRT, another distro based on OpenWRT was merged into libreCMC in 2015

* URL: https://librecmc.org

* (optional) Color in hex:

* (optional) Description and history: libreCMC is a set of fully free embedded Operating Systems for general purpose computers.

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
