### ISSUE TITLE
Add Fire OS

### ISSUE THREAD

**Issue by nicolasmaia** [FabioLolix/LinuxTimeline#130]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name: Fire OS

* Base: Android

* Start date: Nov 2011

* (eventual) Name changes with date: 

* URL: https://developer.amazon.com/apps-and-games/devices

* (optional) Color in hex:

* (optional) Description and history: 

See: https://en.wikipedia.org/wiki/Fire_OS

**Comment by FabioLolix** [comment]
Hello @nicolasmaia and thank you for your patience

Fire OS don't met several requirements for inclusion https://github.com/FabioLolix/LinuxTimeline/issues/158

About the openess Amazon is doing the bare minimum which is publishing an archive with the open source code
