### ISSUE TITLE
Add Firefox OS

### ISSUE THREAD

**Issue by nicolasmaia** [FabioLolix/LinuxTimeline#131]
**Adding a distribution**

* Name: Firefox OS

* Base: None

* Start date: 2012

* (eventual) Name changes with date: 

* URL: https://mozilla.org/firefox/os

* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md

* Stop date: 2016

* Statement URL (if any): https://en.wikipedia.org/wiki/Firefox_OS

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
