### ISSUE TITLE
add KaiOS

### ISSUE THREAD

**Issue by nicolasmaia** [FabioLolix/LinuxTimeline#132]
**Adding a distribution**

* Name: KaiOS

* Base: Firefox OS

* Start date: 2017

* (eventual) Name changes with date: 

* URL: https://www.kaiostech.com/

* Statement URL (if any): https://en.wikipedia.org/wiki/KaiOS

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
