### ISSUE TITLE
Add EuroLinux

### ISSUE THREAD

**Issue by jakub-olczyk** [FabioLolix/LinuxTimeline#134]
**Adding a distribution**

* Name: EuroLinux

* Base: Red Hat, Scientific

* Start date: 2015

* (eventual) Name changes with date: 

* URL: https://euro-linux.com/eurolinux/

* (optional) Color in hex: #005AA5

More information: https://distrowatch.com/table.php?distribution=eurolinux

**Comment by FabioLolix** [comment]
Hello @jakub-olczyk and thanks for your patience,

When I first looked at EuroLinux website in May 2020 I didn't see public images download neither srcrpm downloads and wasn't sure about adding a distro that provided nothing for non-paying customer.

Now there are public downloads and EuroLinux Sp. z o.o. have some obligations to publish packages source depending on their license.

In the meantime I have setted dome rules for inclusion and created an open info archive for all distributions

> Start date: 2015

I want a more precise start date, first day of general availability, precise to the day

For the URL use https://fabiololix.gitlab.io/os/linux/e/eurolinux/

Page code can be found here: https://github.com/FabioLolix/fabiololix.gitlab.io/blob/master/docs/os/linux/e/eurolinux.md
 At the moment EuroLinux page is not on par with the default template https://github.com/FabioLolix/fabiololix.gitlab.io/blob/master/template.txt

**Comment by jakub-olczyk** [comment]
Hey @FabioLolix !

I am not the best person to provide the information right now. Sorry!

But I think that @alaczyz or @AlexBaranowski will provide you with the necessary information as soon as they can.

Cheers!

**Comment by AlexBaranowski** [comment]
Hi!

@jakub-olczyk , thanks for remembering about us!  @FabioLolix I will personally create a pull request with changes in the code (page code to be more precise) probably tomorrow evening. OFC I will provide all the necessary information that you asked about.

Best,
Alex

**Comment by Barnabasz** [comment]
Hi,

I just created a new PR for this issue: https://github.com/FabioLolix/LinuxTimeline/pull/215
Informations that you requested:
Eurolinux 6/7:
start date: 7.15.2015
first day of general availability: 7.15.2015
Eurolinux 8 (opencore free image):
first day of general availability: 05.25.2021

Should I also contribute to https://github.com/FabioLolix/fabiololix.gitlab.io?

Proposed page for eurolinux
```
# EuroLinux

## Description and history

> A the beginning based on Scientific now on RHEL with full binary compatible with it.

> Developed by

EuroLinux<sup>tm</sup>

| username | password |  |
|----------|----------|--|
|  |  |  |


## License & Type

> FOSS


## Packaging and repositories 


|                       |  |
|-----------------------|--|
| Homepage              | <https://en.euro-linux.com/eurolinux/> |
| Homepage backup       |  |
| Based on              | RHEL |
| Status                | Active |
| Architecture          | x86_64 |
| Category              | Server |
| Desktop (default)     |  |
| Desktop (available)   |  |
| Source                | <https://vault.cdn.euro-linux.com/> |
| Download              | <https://en.euro-linux.com/eurolinux/try-eurolinux/> |
| Release model         | Fixed |
| Packaging             | RPM |
| Package management    | yum/dnf |
| Installer             | anaconda |
| Init                  | systemd |
| C library             | glbic |
| Core utils            |  |
| Compiler              | gcc-8.3.1-5.1.el8.x86_64.rpm ? |
| Language              | English |
| Country               | Poland |
| IRC                   | - |
| Forum                 | https://community.euro-linux.com/ |
| Mailing list          | - |
| Docs                  | https://docs.euro-linux.com/ |
| Bugtracker            | <https://github.com/EuroLinux/eurolinux-distro-bugs-and-rfc> |
| Translation           | - |
| Donations             | - |
| Commercial            | Yes |
| Price                 |  Cheapest paid version 139€ (same as FREE one but with support) |
| Social/Contact        | <https://en.euro-linux.com/company/contact/> |
| Social                | <https://pl.linkedin.com/company/eurolinux-sp.-z-o.o.> |
| Social                | <https://www.youtube.com/channel/UCwHwxWySqqWlB4YajqTBPTg> |
| Social                | <https://twitter.com/euro_linux> |
| Social                | <https://www.facebook.com/eurolinux/> |
| ArchiveOS             | <https://vault.cdn.euro-linux.com/> |
| Distrowatch           | <https://distrowatch.com/table.php?distribution=eurolinux> |
| Wikipedia             | https://en.wikipedia.org/wiki/EuroLinux ? |
| on LWN.net            | - |
| Repology              | - |
| In the timeline       |  |


## Build



## Releases

* 23.02.2015 Eurolinux 6/7
* 25.05.2021 Eurolinux 8

## Media coverage



## About this page

> This page code can be found here:

* https://gitlab.com/FabioLolix/fabiololix.gitlab.io/-/tree/master/docs/os
* https://github.com/FabioLolix/fabiololix.gitlab.io/tree/master/docs/os
```

**Comment by FabioLolix** [comment]
> Should I also contribute to https://github.com/FabioLolix/fabiololix.gitlab.io?

Hello @Barnabasz, yes , I want the information before adding new distributions, in the meantime I have update the [page](https://fabiololix.gitlab.io/os/linux/e/eurolinux/) with some fo your informations 

>  Eurolinux 8 (opencore free image):
> \## License & Type
>
> FOSS

I'm not sure opencore and FOSS go hand in hand and https://vault.cdn.euro-linux.com/ is not reachable here.

> | Price                 |  Cheapest paid version 139€ (same as FREE one but with support) |

Can't confirm the price, I've seen only contact us for pricing or similar

> A the beginning based on Scientific now on RHEL with full binary compatible with it.

'now' When?

**Comment by FabioLolix** [comment]
Added with https://github.com/FabioLolix/LinuxTimeline/commit/c0740ad0a918e74991e232ca101838a7370773b6

**Comment by Barnabasz** [comment]
Hi @FabioLolix sorry for late response,

We think that FOSS is proper description because open core and paid are the very same for users in both versions. Paid version includes support hours) 
https://vault.cdn.euro-linux.com/ is in WiP state right now, i will let you knew when it will be finally out.

Prices can by found under this link: https://en.euro-linux.com/offer/price-list/?11194d9e57415ca9b533b31d99621e45 
Pls dont publish this link it will probably change in the future and for now its send to people after asking for it at this form: https://en.euro-linux.com/offer/price-list/

'now' = 25.05.2021 with release of Eurolinux 8 

Could you also remove link to Forum from https://fabiololix.gitlab.io/os/linux/e/eurolinux/, it is still in preparation faze and it shouldn't be published yet.

Thank you for your help,
BR,
Kamil

**Comment by FabioLolix** [comment]
> Prices can by found under this link: https://en.euro-linux.com/offer/price-list/?11194d9e57415ca9b533b31d99621e45
> Pls dont publish this link

Ok

> Could you also remove link to Forum

Done




> 'now' = 25.05.2021 with release of Eurolinux 8

Ok



> We think that FOSS is proper description

Can't write that something is FOSS/OSS when there are no public source

> open core and paid are the very same for users in both versions. Paid version includes support hours)

Aside from support, customers have additional packages/programs/API ?

**Comment by Barnabasz** [comment]
Hi @FabioLolix ,

I'm not sure if I should response hear or create a new issue, but:

sources are public now: https://vault.cdn.euro-linux.com/sources/eurolinux/8/

and no, there are no additional content/features for paying customers, other than support.

Thank you once again for your great help, and please tell me if it is OK to continue in this thread, if not i will create a new issue right away :D

BR,
Kamil

**Comment by FabioLolix** [comment]
Hi @Barnabasz 

Thanks for letting me know,

For future informations about EuroLinux please open an issue on https://github.com/FabioLolix/distroware.gitlab.io
