### ISSUE TITLE
Add Hannah Montana Linux

### ISSUE THREAD

**Issue by SirLotsaLocks** [FabioLolix/LinuxTimeline#139]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name: Hannah Montana Linux

* Base: Kubuntu

* Start date: 2008

* (eventual) Name changes with date: 

* URL: http://hannahmontana.sourceforge.net/

* (optional) Color in hex: #993399

* (optional) Description and history: talk about the project, for adding to distributions.md

**Discontinuing a distribution** 

* Name: Hannah Montana Linux

* Stop date:  June 30, 2009

* Statement URL (if any):

**Comment by FabioLolix** [comment]
I will not add this type of distros
