### ISSUE TITLE
Distributions not showing up in timeline because of #N and // N in first column

### ISSUE THREAD

**Issue by IngerAlHaosului** [FabioLolix/linuxtimeline#14]
Hi,
I noticed that several distributions in the gldt.csv file have #N or // N instead of N in the first column and because of this they don't show  up in the timeline. Is there a reason for this or was this done by accident?

Lines affected by this are:
* for // N
112 Mystras OS
113 Xinutop
145 INX
171 NodeZero
173 Blackbuntu
175 iQunix OS
177 icefeast
178 Sn0wL1nuX
179 Bigtux
180 Jeoss
181 Redo
183 Freezy
185 Arduloko OS
187 Hybride
189 jfLinux
190 MLIPenguin-OS
191 AtlasX
255 Cultix
256 SprezzOS

* for #N 
58 Joatha
142 Maryan
158 Zenix OS
162 Dax OS
174 P@xtreme	
191 Airinux
193 Vulnix
236 Sword OS
244 Conducit
250 srvRX live
335 Anthon
475 AnikOS
476 OccupyOS
484 FireFly
491 LDR
497 Nosonja
558 AtheOS
559 Syllable
572 Saluki
627 Ophone

**Comment by FabioLolix** [comment]
Hello,

This is a wanted behavior, it's essentially commentig the line

#N indicate not relevant discontinued distro, one release only for example

//N indicate distribution in waiting list, similar to distrowatch https://distrowatch.com/table.php
