### ISSUE TITLE
add Replicant

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#144]
**Adding a distribution**

* Name: Replicant

* Base: Android, CyanogenMod and LineageOS

* Start date: 2011-04-26

* (eventual) Name changes with date: 

* URL: https://www.replicant.us/

* (optional) Color in hex: #FB0007

* (optional) Description and history: talk about the project, for adding to distributions.md
Related pages:
https://en.wikipedia.org//wiki/Replicant_(operating_system)
https://redmine.replicant.us/projects/replicant/wiki
https://www.gnu.org/distros/free-non-gnu-distros.html

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
