### ISSUE TITLE
add openEuler

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#146]
**Adding a distribution**

* Name: [openEular](https://openeuler.org/) and [EularOS](https://developer.huaweicloud.com/ict/cn/site-euleros/euleros)

* Base: CentOS

* Start date: 2019-09-19, and EularOS start in 2010.

* (eventual) Name changes with date: 

* URL: https://openeuler.org/

* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md
openEular based on CentOS, and it has an enterprise version called EularOS. 
There are also many openEuler Based OS Distribution:
- [iSoft Server OS（普华）](http://www.i-soft.com.cn/)
- [HopeEdge, IoT system](http://www.hoperun.com/)
- [TurboLinux Enterprise Server 15](http://www.turbolinux.cn)
- [EulixOS](https://eulixos.com/)

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
