### ISSUE TITLE
Add GNOME OS

### ISSUE THREAD

**Issue by DestroyerXyz** [FabioLolix/LinuxTimeline#148]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
GNOME OS
* Base:
None(Built from Source)
* Start date:
Announced July 2020(Not released yet)
* URL:
(Iso Download Link only) gnome-build-meta.s3.amazonaws.com/gnome_os_installer.iso
* (optional) Color in hex:
#0000

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
