### ISSUE TITLE
Add Garuda Linux

### ISSUE THREAD

**Issue by DestroyerXyz** [FabioLolix/LinuxTimeline#149]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
Garuda Linux
* Base:
Arch Linux
* Start date:
August 2020
* URL:
Garuda Linux.in
* (optional) Color in hex:
#27bffa

**Comment by xingjiapeng** [comment]
https://github.com/FabioLolix/LinuxTimeline/blob/e4f0b66f604d2d7c6b919dcbc77a49a095b26703/gldt.csv#L381

I think they are different.

**Comment by DestroyerXyz** [comment]
The domain mentioned in this is no longer registered

**Comment by DestroyerXyz** [comment]
I found a GarudaOne profile on GitHub but doesn't look like it is the creator of Garuda(PCLinuxOS) so it is probably dead

**Comment by FabioLolix** [comment]
> I think they are different.

They are different, I have seen some activity of the developer of the Arch based

**Comment by DestroyerXyz** [comment]
Maybe you should flag this as TOO YOUNG??

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
