### ISSUE TITLE
Please Add Linux-Distribution Keysoft

### ISSUE THREAD

**Issue by z1tr0t3c** [FabioLolix/linuxtimeline#15]
**NOTE: If the issue is NOT about adding/discontinuing a distro, delete
these out.**

Distro name*: Keysoft

Start date*: 27.12.2014

Stop date:

URL*: https://keysoft-technology-productions.com

*Must be filled out.

**Comment by FabioLolix** [comment]
I will add this in the near future

**Comment by FabioLolix** [comment]
Added with commit https://github.com/FabioLolix/linuxtimeline/commit/ff9155b981868128d9c0e90c8d38ea035bbe2fbf

**Comment by z1tr0t3c** [comment]
The URL for Keysoft has been changed.
New URL is: http://keysoft.zitrotec.de
