### ISSUE TITLE
Add Artix Linux

### ISSUE THREAD

**Issue by DestroyerXyz** [FabioLolix/LinuxTimeline#150]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
Artix Linux
* Base:
Arch Linux
* Start date:
2017
* (eventual) Name changes with date: 
Artix OpenRC(2012 - 2017)
* URL:
artixlinux.org
* (optional) Color in hex:
#2eaed4
* (optional) Description and history: talk about the project, for adding to distributions.md
Artix OpenRC and ManjaroRC started in 2012 and combined into Artix Linux in 2017

**Comment by xingjiapeng** [comment]
https://github.com/FabioLolix/LinuxTimeline/blob/e4f0b66f604d2d7c6b919dcbc77a49a095b26703/gldt.csv#L542

it is exists.

**Comment by DestroyerXyz** [comment]
Oh sorry. My bad. I searched for it in latest svg but didn't get a result. After you told me I checked manually and it was there. Maybe Google drive's search feature is broken in svg.
