### ISSUE TITLE
Add Base Distro Logos

### ISSUE THREAD

**Issue by DestroyerXyz** [FabioLolix/LinuxTimeline#153]
![1000px-Android_logo_2019 svg](https://user-images.githubusercontent.com/70191184/93665491-831c5f80-fa94-11ea-9325-eb5b5b680064.png)
![1200px-Archlinux-icon-crystal-64 svg](https://user-images.githubusercontent.com/70191184/93665499-8a436d80-fa94-11ea-975e-1946c69d2594.png)
![1200px-Gentoo_Linux_logo_matte svg](https://user-images.githubusercontent.com/70191184/93665503-8e6f8b00-fa94-11ea-9f74-8668bcb74f6c.png)
![download](https://user-images.githubusercontent.com/70191184/93665506-992a2000-fa94-11ea-922f-8d4501bcd0bf.png)
![redhat-logo-259A623E59-seeklogo com](https://user-images.githubusercontent.com/70191184/93665510-9deed400-fa94-11ea-8448-45763f858da3.png)

**Comment by DestroyerXyz** [comment]
Found Better Logos
Added in GitLab Issue "#147" as GitHub does not support uploading SVGs

**Comment by FabioLolix** [comment]
All logos lacks copyright, license and eventual permission to use

**Comment by konimex** [comment]
Please note that the Red Hat logo is outdated and you'll likely need *new* permission notice from Red Hat. Even then, I don't think Wikimedia Commons will accept a timeline with Red Hat (or any non-free) logo. Gentoo is CC-BY-SA so I think it's fine to include [Wikimedia's SVG](https://commons.wikimedia.org/wiki/File:Gentoo_Linux_logo_matte.svg). I think Arch and Android logo public domain according to Wikimedia.

**Comment by DestroyerXyz** [comment]
Yeah I uploaded the new RedHat Logo on GitLab and understand that it needs permission but you can add the other ones from the GitLab Issue and I actually got the Gentoo logo from their official page and not wikimedia
