### ISSUE TITLE
Info about Rocks

### ISSUE THREAD

**Issue by FabioLolix** [FabioLolix/LinuxTimeline#159]
Hello @KoheiIchikawa, Rocks is still developed?

**Comment by KoheiIchikawa** [comment]
Sorry, but I'm not a developer of Rocks, and not sure their current development activities.

**Comment by FabioLolix** [comment]
Ok, I've contacted you because you are the only public person listed in https://github.com/rocksclusters

**Comment by FabioLolix** [comment]
Pinging Philip @ppapadopoulos who commited to core, roll-server, etc..

**Comment by FabioLolix** [comment]
Discontinued with 18d5fd52e45f8b6e324d96095d5ef901a3f387f3
