### ISSUE TITLE
LFS influenced Crux

### ISSUE THREAD

**Issue by Mathnerd314** [FabioLolix/LinuxTimeLine#16]
See here: http://lists.linuxfromscratch.org/pipermail/blfs-support/2001-September/010620.html
> Per Liden who made the distro gives thanks to Gerard Beekmans ... For creating the "LinuxFromScratch" how-to

**Comment by FabioLolix** [comment]
Added a connector with commit https://github.com/FabioLolix/LinuxTimeLine/commit/bed7108b32c603e01d8281d75e86aa3fa35da140 
Thanks
