### ISSUE TITLE
Debian 8 is EOL, SteamOS is or will be EOL?

### ISSUE THREAD

**Issue by FabioLolix** [FabioLolix/LinuxTimeline#167]
* https://www.debian.org/News/2020/20200709
> The Debian Long Term Support (LTS) Team hereby announces that Debian 8 "jessie" support has reached its end-of-life on June 30, 2020, five years after its initial release on April 26, 2015.
***
* https://www.game-debate.com/news/25482/valve-counts-to-3-steamos-3-0-is-inbound-codenamed-clockwerk
> Valve is pushing ahead with SteamOS 3.0, in its Linux-based operating system designed for Steam gaming. 

25 July 2018
* https://repo.steampowered.com/steamos/dists/ Last edit date for clockwerk: 2019-Feb-28
***
* https://store.steampowered.com/steamos/

**Comment by SebiderSushi** [comment]
Steam announced the [Steam Deck](https://www.steamdeck.com) to start shipping in "December 2021", with its operating system specified as `SteamOS 3.0 (Arch-based)` in its [tech specs](https://www.steamdeck.com/tech).

**Comment by FabioLolix** [comment]
Yeah, I have seen it

Also note that OSes only bundled with hardware are not welcome here

**Comment by SebiderSushi** [comment]
noted

**Comment by FabioLolix** [comment]
Fixed with https://github.com/FabioLolix/LinuxTimeline/commit/20f531071e2cf57102348f80ce7476c1280e0271
