### ISSUE TITLE
Thinstation based on CRUX

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#173]
* Name: Thinstation
## Issue

Thinstation based on CRUX according to distrowatch:
https://distrowatch.com/table.php?distribution=thinstation
(probably started on 2012-02-10?)

**Comment by FabioLolix** [comment]
Fixing with this https://github.com/FabioLolix/LinuxTimeline/commit/ef555a4224dfd06244c613f20b15cbdee8405506 at the moment, will return on this later on
