### ISSUE TITLE
Chakra discontinued

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#176]
* Name: Chakra
* Discontinuation statement URL if available
https://distrowatch.com/table.php?distribution=chakra

**Comment by FabioLolix** [comment]
I left this open because while iso images have not been published for a while at first sight packages where still updated, with today distrowatch weekly have been reported that it is effectively discontinued and website took offline (confirmed)

**Comment by FabioLolix** [comment]
Fixed with https://github.com/FabioLolix/LinuxTimeline/commit/75a1087894de0197496f30800e3a4bfa69688bcb
