### ISSUE TITLE
Bardinux discontinued

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#177]
* Name: Bardinux
* Discontinuation statement URL if available
https://distrowatch.com/table.php?distribution=bardinux

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/202fb896f9b8bbeb60719630f38a77257cbf23b6

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/b240a3d3847c83322817edf7d760e4657d974f86
