### ISSUE TITLE
Draco discontinued

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#178]
* Name: Draco
* Discontinuation statement URL if available
https://distrowatch.com/table.php?distribution=draco

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/8180ae255a18aeafa1d9b706edf0f0745e150975

(At the time I've re-add it because of this https://sourceforge.net/projects/draco/files/live/)
