### ISSUE TITLE
Red Hat Enterprise is based on Fedora

### ISSUE THREAD

**Issue by CodeDoctorDE** [FabioLolix/LinuxTimeline#181]
* Name: Red Hat Enterprise

## Issue

The newest red hat enterprise is based on fedora: https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-linux/#_history_of_red_hat_enterprise_linux_and_fedora

**Comment by FabioLolix** [comment]
Duplicate of #66
