### ISSUE TITLE
OSMC is based on Debian not Raspbmc

### ISSUE THREAD

**Issue by jb2cool** [FabioLolix/LinuxTimeline#183]
* Name: OSMC

## Issue

OSMC although created by the founders of Raspbmc is is not based on Raspbmc but is instead based on Debian. Raspbmc should be discontinued a of June 2015 and OSMC should be considered a branch of Debian from this same date

**Comment by FabioLolix** [comment]
Hello Jason and thank you for your patience.

I have been informed that the information is correct, I'll fix it in the next days

by the way, Name: is about distributions not yours :)

**Comment by FabioLolix** [comment]
Fixed with https://github.com/FabioLolix/LinuxTimeline/commit/61290d5b74b387ee49a06cafba40b2f8af3325a4
