### ISSUE TITLE
KaOS

### ISSUE THREAD

**Issue by ShalokShalom** [FabioLolix/LinuxTimeline#19]
Hi there 

KaOS is independent 

https://kaosx.us/
http://distrowatch.com/table.php?distribution=kaos

Its listed as Arch based, most likely since it use Pacman.

**Comment by FabioLolix** [comment]
Hi
How much there is from Arch except for Pacman?

**Comment by ShalokShalom** [comment]
Nothing.

**Comment by FabioLolix** [comment]
Fixed with commit https://github.com/FabioLolix/LinuxTimeline/commit/6d387ef04ef981c1741f02af9e15a608aa2aa5a3
Thanks
