### ISSUE TITLE
Mer merged with SailfishOS

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#193]
* Name: Mer
* Discontinuation statement URL if available
https://blog.jolla.com/message-in-a-bottle/

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/37a6936c2de8b9a4347a46f7d923bf4c860c0103

https://forum.sailfishos.org/t/changes-needed-to-merge-the-project-names-to-sailfish-os/1672
