### ISSUE TITLE
Problem with openSUSE and SUSE

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#194]
* Name: SUSE

## Issue
According to the openSUSE's wiki:
https://en.opensuse.org/Archive:SUSE_Linux_10.0
https://en.opensuse.org/Archive:OpenSUSE_10.2
> The distribution was renamed from SUSE Linux to openSUSE to avoid confusion with the SUSE Linux Enterprise Products.
(openSUSE instead of OpenSUSE)

and according to [DistroWatch](https://distrowatch.com/table.php?distribution=sle), SLE is based on openSUSE

**Comment by FabioLolix** [comment]
Hello @OkayPJ, yesterday I have started looking at the opensuse archive, I should fix this in about a week

**Comment by FabioLolix** [comment]
Done with https://github.com/FabioLolix/LinuxTimeline/commit/1f440a6f624b4959b1ae35120f716c7e2c397bbb
