### ISSUE TITLE
Qomo Linux discontinued

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#196]
* Name: Qomo
* Discontinuation statement URL if available
https://distrowatch.com/table.php?distribution=qomo

I found the distro is still active until 2015-1-1, and this is the last version I can found.
http://www.linuxren.org.cn/forum.php?mod=viewthread&tid=74021

**Comment by xingjiapeng** [comment]
[The community of Qomo](http://www.linuxren.org.cn) is still there, but it's not active any more

**Comment by FabioLolix** [comment]
Done https://github.com/FabioLolix/LinuxTimeline/commit/2d26cb3b96d11c0720d5172932009b451f3f2909
