### ISSUE TITLE
dead distro

### ISSUE THREAD

**Issue by JulienAMOURIQ** [FabioLolix/LinuxTimeline#20]
**Template for adding/discontinuing a distro, all non optional fields are mandatory**

*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Discontinuing a distro**

* Distro name: chameleonOs

* Stop date: 2011

* Statement URL (if any): https://chameleonos.wordpress.com/newsblog/

**Comment by FabioLolix** [comment]
Fixed with commit https://github.com/FabioLolix/LinuxTimeline/commit/e19550f5ab7e5410d0c7d828c93c358ef666c2e6

* Discontinued Unity Linux, last release 2012-03-03 according to distrowatch.com
* Blacklisted ChameleonOS, one release only

Thanks
