### ISSUE TITLE
GrapheneOS

### ISSUE THREAD

**Issue by u-spec-png** [FabioLolix/LinuxTimeline#203]
* https://grapheneos.org/
* https://github.com/GrapheneOS

**Comment by FabioLolix** [comment]
Hello, I'm aware of the existence of GrapheneOS

https://github.com/FabioLolix/fabiololix.gitlab.io/tree/master/docs/os/linux/andrd

**Comment by FabioLolix** [comment]
Hello, I'm aware of the existence of GrapheneOS

https://github.com/FabioLolix/fabiololix.gitlab.io/tree/master/docs/os/linux/andrd
