### ISSUE TITLE
Microsoft CBL-Mariner

### ISSUE THREAD

**Issue by timothybrush** [FabioLolix/LinuxTimeline#209]
Microsoft open sourced its internal Linux distribution (CBL-Mariner)
- https://github.com/microsoft/CBL-Mariner
- https://en.wikipedia.org/wiki/CBL-Mariner

RPM-based with acknowledgements to Photon OS Project, Fedora Project, and Linux from Scratch.

Earliest commit on GitHub - Aug 17, 2020 (https://github.com/microsoft/CBL-Mariner/releases?after=1.0.20200817)

**Comment by FabioLolix** [comment]
Hello, yeah I have seen it in the news, blank page created at the info archive https://github.com/FabioLolix/fabiololix.gitlab.io/commit/f316d8eec1f5e5b0c46867539cb2114b1cf3575d
