### ISSUE TITLE
Several Arch-based distro

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#211]
* [EndeavourOS](https://endeavouros.com/), started from [2019-06-23](https://endeavouros.com/uncategorized/welcome-to-endeavouros/)
* [Archman](https://archman.org/)
* [ArchStrike](https://archstrike.org/), started from [2016-06-26](https://archstrike.org/news/10001)

**Comment by FabioLolix** [comment]
I'm aware of the existence of all the 3 distros

EndeavourOS have been discussed here before, 

about Archman I haven't tried it yet but some time ago wasn't positively impressed by their custom repository

about Archstrike I haven't tried it yet, it has been on hiatus for several years (at least the releases) and had read that they were accused of importing Blackarch packages back in the day, haven't investigated about it

For Archman and ArchStrike I created the page at the info archive now

https://github.com/FabioLolix/fabiololix.gitlab.io/tree/master/docs/os/linux/a

https://github.com/FabioLolix/fabiololix.gitlab.io/tree/master/docs/os/linux/e
