### ISSUE TITLE
Checked your site on the svg in wikipedia.

### ISSUE THREAD

**Issue by redrye** [FabioLolix/LinuxTimeline#213]
Checked your site on the svg in wikipedia. The site it redirects to, has no information.

**Comment by FabioLolix** [comment]
Yeah, I know, only a couple of pages are fulfilled, the site is completely open source and anyone can contribute, it is a lot of work to do,

**Comment by redrye** [comment]
Ok I understand now. Maybe I could help. Ill take a look at everything.

**Comment by FabioLolix** [comment]
A fairly complete page is BBQLinux https://fabiololix.gitlab.io/os/linux/b/bbqlinux/

There isn't much documentation yet

The site is running on Gitlab pages but the code is also hosted here on github https://github.com/FabioLolix/fabiololix.gitlab.io

The pages are done by coping the default template template.txt in the main directory as for example /docs/os/linux/b/bbqlinux.md

For the distro reviews I will not spare technical criticism and I will not make condescending reviews

**Comment by FabioLolix** [comment]
I'm quite different from some other reviewers of which I read articles, here's my take on 4MLinux

https://fabiololix.gitlab.io/os/linux/0-9/4m/#
