### ISSUE TITLE
Different visualisation perspective

### ISSUE THREAD

**Issue by Coool** [FabioLolix/LinuxTimeline#217]
[Image](https://user-images.githubusercontent.com/19638095/97118180-e25f3680-1708-11eb-8bef-1ebe025e1374.png) format is crap, without references and different view points. Would be great make like genealogy software where you can track every point of merge, split and so on. And with references, comments and etc. What can community suggest. I would like covert  [CSV](https://github.com/FabioLolix/LinuxTimeline/blob/master/ldt.csv) file differently.

**Comment by FabioLolix** [comment]
> [Image](https://user-images.githubusercontent.com/19638095/97118180-e25f3680-1708-11eb-8bef-1ebe025e1374.png) format is crap, without references and different view points

> I would like covert [CSV](https://github.com/FabioLolix/LinuxTimeline/blob/master/ldt.csv) file differently.

Default convert is to SVG, PNG is a 'plus' to use on regular image vievewers

in the SVG 'distro names' (now) link to my open archive to give more context, history, reviews, etc.. (the archive is not even 1% full)

> Would be great make like genealogy software where you can track every point of merge, split and so on. And with references, comments and etc. What can community suggest.

You're not the first to suggest something like that

**Comment by Coool** [comment]
FabioLolix, thanks for your responsive replay. Linux distros world is crap too. Somebody asked Linus Torvalds which is your best distro. Non. He just compile all from source. I will try update my best distros template files. Do you accept push updates?

**Comment by FabioLolix** [comment]
> Somebody asked Linus Torvalds which is your best distro. Non. He just compile all from source.

I've read he didn't want to endorse a distro over another, I'm not sure he's compiling everything from source




> Do you accept push updates?

Sure, I'm looking for contributors
