### ISSUE TITLE
RancherOS is discontinued

### ISSUE THREAD

**Issue by mcen1** [FabioLolix/LinuxTimeline#225]
* Name: RancherOS
* Discontinuation statement URL if available
https://github.com/rancher/os/issues/3000#issuecomment-679221210
https://github.com/rancher/docs/issues/2508
https://forum.devtalk.com/t/rancheros-is-in-end-of-life/6466
Wish I had more concrete links, but they're now behind SUSE's website it seems. But we used RancherOS and I believe it went out of support last year, and as such we migrated off of it to CentOS at my company.

**Comment by FabioLolix** [comment]
Thanks for letting me know, fixed with https://github.com/FabioLolix/LinuxTimeline/commit/e906f08dd67c2d090d406f87539aa9b1c92e6ef5
