### ISSUE TITLE
CentOS EOL

### ISSUE THREAD

**Issue by FabioLolix** [FabioLolix/LinuxTimeline#226]
https://www.centos.org/cl-vs-cs/

* CentOS Linux 7 EOL: 2024-06-30
* CentOS Linux 8 EOL: 2021-12-31

**Comment by RefriZaddo** [comment]
i'm glad you know what i was gonna tell you

**Comment by RefriZaddo** [comment]
I'm glad you understand at least part of what I was gonna say

**Comment by RefriZaddo** [comment]
oh wait i said it in jan 3

**Comment by FabioLolix** [comment]
Note to self on the CentOS 7 based SME Server, v10.1 is deprecated but v11 isn't out yet, 

* https://forums.koozali.org/index.php/topic,55196.0.html
* https://forums.koozali.org/index.php/topic,55139.0.html

**Comment by FabioLolix** [comment]
Fixed with https://github.com/FabioLolix/LinuxTimeline/commit/176dcde978e0ad2009ff419fa27b19299890c954
