### ISSUE TITLE
Xinutop problem

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#227]
* Name: Xinutop

## Issue
https://github.com/FabioLolix/LinuxTimeline/blob/9b535abfdf35353e9162a79e30972a91d4b1f445/ldt.csv#L174

According to [Marinux Website](https://marinux.tuxfamily.org/) (I cannot found any more information about Xinutop), Xinutop is based on Debian Jessie. I checked it and found an package named xubuntu-system-tools-old, which is not existing in the debian  package. 

In the timeline, the Xinutop is on the fork of Xubuntu, but it seems based on Debian, but contains Xubuntu tools.

**Comment by FabioLolix** [comment]
Good catch, I'll investigate, I'm not familiar with this distro

**Comment by FabioLolix** [comment]
Done https://github.com/FabioLolix/LinuxTimeline/commit/ef7f772dc50d900dc0768be87bb73e3408aa28c4 https://download.tuxfamily.org/xinutop/xinutop-nav-x86/changes.txt
