### ISSUE TITLE
CBL-Mariner, Linux distibution from Microsoft (2020)

### ISSUE THREAD

**Issue by X1Z53** [FabioLolix/LinuxTimeline#228]
Name: CBL-Mariner
Manufacturer: Microsoft
Release Date: September 16, 2020
Source: https://github.com/microsoft/CBL-Mariner
Wiki: https://en.wikipedia.org/wiki/CBL-Mariner

**Comment by FabioLolix** [comment]
https://github.com/FabioLolix/LinuxTimeline/issues/209
