### ISSUE TITLE
Rocky Linux, RHEL Based (2021)

### ISSUE THREAD

**Issue by X1Z53** [FabioLolix/LinuxTimeline#229]
Name: Rocky Linux
Release Date: 21 June 2021
Source: https://git.rockylinux.org/original/rpms/rocky-release/-/tree/r8
Wiki: https://en.wikipedia.org/wiki/Rocky_Linux

**Comment by FabioLolix** [comment]
https://github.com/FabioLolix/LinuxTimeline/pull/198
