### ISSUE TITLE
SteamOS 3.0

### ISSUE THREAD

**Issue by RyanHakurei** [FabioLolix/LinuxTimeline#232]
With the near release of the Arch-based SteamOS, is it possible that it will be added to the timeline under Arch? There's a provision in the chart for when distros re-base so it's be good to have SteamOS "revived" due to the 3.0 release.

I know it's mentioned in #167 that hardware specific releases aren't allowed, but Valve is planning on a general SteamOS 3.0 release that can be installed on anything. It's mentioned on the [official Valve page](https://help.steampowered.com/en/faqs/view/1B71-EDF2-EB6D-2BB3) for the Steam Deck recovery image: "SteamOS 3 proper will come out sometime after launch (and even then it may not work on your toaster)."

**Comment by FabioLolix** [comment]
One year after the general SteamOS will be out it could be added
