### ISSUE TITLE
Error: unknown icon file format: io/os/linux/d/deepin

### ISSUE THREAD

**Issue by cyclamenkde** [FabioLolix/LinuxTimeline#233]
* Name:
ldt.csv
## Issue
![image](https://user-images.githubusercontent.com/729456/162140187-34f10600-185e-4f73-a43c-dec5610a03ab.png)

Error: unknown icon file format: io/os/linux/d/deepin

I found the problem in ldt.csv file
Line 358 and 484 is missing a comma.
`
"N","deepin","#15A7E5","Debian","2015.12.30",,"https://distroware.gitlab.io/os/Linux/d/deepin",,,,,,,,,,
"N","Stresslinux","#000","S.u.S.E Linux","2003.07.4","2014.11.25","https://distroware.gitlab.io/os/Linux/s/stresslinux",,,,,,,,,,
`
![image](https://user-images.githubusercontent.com/729456/162139829-714c7107-e5e0-4a95-9bc0-0a095ee7a037.png)
![image](https://user-images.githubusercontent.com/729456/162139949-2da6d8d4-ed1d-4883-87c9-f2f6dc886ab2.png)
After adding the missing comma, success:
![image](https://user-images.githubusercontent.com/729456/162140490-b9ab97c5-6a1b-4e70-9afa-df6ec48ecb9b.png)

**Comment by FabioLolix** [comment]
Thanks for reporting, I did not encounter this error

```
$ sh build.sh svg
==> Generating ldt.svg...
gnuclad 0.2.4: ldt.csv => dist/ldt.svg
Computing cladogram for 550 nodes, 129 connectors and 7 domains...
Done
==> Generated dist/ldt.svg
```

How do you installed `gnuclad`?
