### ISSUE TITLE
Add Rocky Linux/AlmaLinux, 2 RHEL-based distros released in 2021.

### ISSUE THREAD

**Issue by RefriZaddo** [FabioLolix/LinuxTimeline#236]
Will be added **ONLY**  distributions that have a fullfilled page at the [info archive](https://distroware.gitlab.io/) 
and follow the [Timeline direction](https://github.com/FabioLolix/LinuxTimeline/issues/158)

The info archive code is both at:

* https://gitlab.com/Distroware/distroware.gitlab.io
* https://github.com/FabioLolix/distroware.gitlab.io

* The timeline direction can be discussed here: [Timeline direction discussion](https://github.com/FabioLolix/LinuxTimeline/issues/157)

**Comment by FabioLolix** [comment]
Hello, I'm aware of their existence and they will be included in the next release https://github.com/FabioLolix/LinuxTimeline/commit/caf4b7fbc5982342b7a3b5519ecbe392191443bb
