### ISSUE TITLE
Netrunner Wrong Info

### ISSUE THREAD

**Issue by RefriZaddo** [FabioLolix/LinuxTimeline#241]
* Distro Name: Netrunner

## Issue
Actually, Netrunner stood there(correct), enjoying life until today, and in 2016, Hawaii OS died(correct), Netrunner gave birth to an entirely unrelated distro, Maui, based on KDE Neon(fix), which died in 2017, and while Maui lived, People from ArchiveOS thought Netrunner died, and when Maui died, Netrunner got all the users back. And its last version launched in 2021(fix). It suddenly died without even getting to bullseye. So now, we gotta live with KDE Neon or Kubuntu as our KDE-including distros then...

**Comment by FabioLolix** [comment]
Hello, 

> Maui, based on KDE Neon(fix), which died in 2017

Maui (Maui Linux) from Netrunner was present but is currently blacklisted because its development lasted less then 2,5 years (about 1 year actually)

> And its last version launched in 2021(fix)

Netrunner based on Debian is currently active in the graph, what should I fix?

***
By the way, ArchiveOS is putting 2 different distros under the name Maui, one is Maui/Maui Linux by Netrunner and the other is Maui OS which was developed by Pier Luigi Fiorini (and others?)

**Comment by RefriZaddo** [comment]
da fuq

**Comment by RefriZaddo** [comment]
add Maui as KDE Neon-based and discontinue it in 2017

**Comment by RefriZaddo** [comment]
i don't see any new version of Netrunner based on Debian

**Comment by RefriZaddo** [comment]
on the official website

**Comment by RefriZaddo** [comment]
now it's just some kind of extended support i think

**Comment by FabioLolix** [comment]
Last release has been on February 20, 2021, distributions are considered discontinued 3 years after the last release

**Comment by RefriZaddo** [comment]
So Netrunner will be considered active until normal CentOS' EOL?
And in 2027, CentOS will be discontinued?

Em sáb, 10 de dez de 2022 18:21, Fabio Loli ***@***.***>
escreveu:

**Comment by RefriZaddo** [comment]
I mean
normal CentOS will end in 2024
Leaving just CentOS stream.

Em ter, 3 de jan de 2023 00:56, Louco Por refri ***@***.***>
escreveu:

**Comment by FabioLolix** [comment]
> So Netrunner will be considered active until normal CentOS' EOL?

Netrunner is based on Debian, I guess you are confusing Netrunner with Nethserver?

About Nethserver, it is still based on CentOS 7 and haven't put a version 8 out yet, from https://www.nethserver.org/nethserver-8/

`While NethServer 7 is an operating system built on top of CentOS 7 and It is heavily-coupled with the underlying OS, NethServer 8 is a container orchestrator and is OS-agnostic.`

> normal CentOS will end in 2024
Leaving just CentOS stream.

Yes, https://github.com/FabioLolix/LinuxTimeline/issues/226

**Comment by FabioLolix** [comment]
Netrunner OS 23 “Vaporwave” Launches Based on Debian GNU/Linux 11 “Bullseye”

https://9to5linux.com/netrunner-os-23-vaporwave-launches-based-on-debian-gnu-linux-11-bullseye

**Comment by RefriZaddo** [comment]
ooooooooooooh so they skipped 22.1

Em sáb., 21 de jan. de 2023 às 08:05, Fabio Loli ***@***.***>
escreveu:

**Comment by RefriZaddo** [comment]
also I meant in your timeline but since netrunner launched a new version,
nevermind

**Comment by FabioLolix** [comment]
> also I meant in your timeline

I don't get what you mean

**Comment by RefriZaddo** [comment]
I meant according to the timeline (that 3 years after last release thing)

**Comment by RefriZaddo** [comment]
welp nvm
