### ISSUE TITLE
There's something wrong about Pear OS

### ISSUE THREAD

**Issue by RefriZaddo** [FabioLolix/LinuxTimeline#243]
* Name: Pear OS

## Issue
Pear OS actually got revived in 2019 as pearOS, and before 2022, it was based on Ubuntu, and now, it has two editions: Standard(no actual edition name, Ubuntu-based) and NiceC0re(Arch-based).
Even though ArchiveOS and DistroWatch say it's discontinued, it's not. It just became unknown currently. In 2021 a new website was made for it, [pearos.xyz](https://pearos.xyz).

**Comment by RefriZaddo** [comment]
Also, NiceC0re uses KDE Plasma and the standard pearOS is like Netrunner, no new releases but still supported.

**Comment by FabioLolix** [comment]
I've heard about a new Pear OS, this seems not related to the old one

> Even though ArchiveOS and DistroWatch say it's discontinued, it's not.

The original project is discontinued

About the old one it lasted for so little time that I should blacklist it

**Comment by RefriZaddo** [comment]
so put in the new one

**Comment by FabioLolix** [comment]
> so put in the new one

Not now, it don't met at least one requirement and have several quality issues
