### ISSUE TITLE
Nova came back in 2019

### ISSUE THREAD

**Issue by RefriZaddo** [FabioLolix/LinuxTimeline#244]
* Name: Nova

## Issue
In version 2.1 of Nova(June 2010), its base was changed to Ubuntu, and in 2019 it came back as still Ubuntu-based

**Comment by FabioLolix** [comment]
Yes, I've been made aware of that, it don't have any public development at first sight, I've send one mail for now to them; without reply

**Comment by FabioLolix** [comment]
Please check open issues first #133

**Comment by RefriZaddo** [comment]
i got that info on wikipedia

**Comment by RefriZaddo** [comment]
also Nova got a development halt between 2016 and 2019

**Comment by RefriZaddo** [comment]
so maybe add another type of line, like a "halt" line or something

**Comment by FabioLolix** [comment]
> so maybe add another type of line, like a "halt" line or something

That don't exist in gnuclad

**Comment by RefriZaddo** [comment]
Check Nova's wikipedia page

At least add a 2nd Nova entry in Ubuntu - 2019
