### ISSUE TITLE
api to LinuxTimeline

### ISSUE THREAD

**Issue by ghost** [FabioLolix/LinuxTimeline#246]
Hi.

I would like to know if there is any api in LinuxTimeline. Is there any api in LinuxTimeline, so I can query linux distros by datetime?

**Comment by FabioLolix** [comment]
Hi, no there isn't

**Comment by FabioLolix** [comment]
No, I'm not a developer

**Comment by FabioLolix** [comment]
The main thing is the .CSV file [ldt.csv](https://github.com/FabioLolix/LinuxTimeline/blob/main/ldt.csv) you can find the dates there
