### ISSUE TITLE
Next release will be in 2024

### ISSUE THREAD

**Issue by FabioLolix** [FabioLolix/LinuxTimeline#249]

**Comment by Dacid99** [comment]
Hi FabioLolix ,
do you still plan on making a new release this year? 
Thanks for the great work!

**Comment by aidan-gibson** [comment]
🥺

**Comment by FabioLolix** [comment]
Hello

Likely I will make a new release this year (at the end of October) but it will be a very small release

Searching info is time consuming, between January and August I have never been busier like this in my life but the hard part is passed now

I'm also interested in making an opinionated variant of the timeline without remixes/respin and abandoned proprietary

**Comment by FabioLolix** [comment]
btw just a day before Dacid99 comment I made the first draft for the complementary blog https://github.com/FabioLolix/fabiololix.github.io/commit/c567e6a5458251779f3c6810c3ea5b4bbd6cd253

**Comment by Dacid99** [comment]
Thats amazing, thanks for the great news! 
Dont forget to take some time to relax, you deserve it and whether the release comes out one week earlier or later doesnt matter 😄
But as soon as it's out Ill print it as a poster and put it up in my office 🥳
PS I have just subscribed to the rss of your blog

**Comment by FabioLolix** [comment]
New release is out https://github.com/FabioLolix/LinuxTimeline/commit/ca0938ffb93dafbb6ebb368993347d42196de858 

https://github.com/FabioLolix/LinuxTimeline/releases/tag/v24.10

The most underwhelming release so far but wouldn't wait another year at this point

> whether the release comes out one week earlier or later doesn't matter 😄

Actually I have a self imposed deadline of the Linux Day (today) or at worst by the end of October

>  But as soon as it's out Ill print it as a poster and put it up in my office 🥳

Can you send me a photo later?

>  PS I have just subscribed to the rss of your blog

Thanks! It will be some time for the posts though
