### ISSUE TITLE
TinyCore

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#25]
**Adding a distro**

* Distro name: TinyCore Linux

* Base distro: None

* Start date: January 5, 2009

* URL: http://tinycorelinux.net/

* (optional) Description:
see also https://en.wikipedia.org/wiki/Tiny_Core_Linux
In the meantime there are a variants which can also use Debian packages (from Debian or Ubuntu repositories).
Robert Shingledecker is a former developer of Damn Small Linu, but TinyCore is not based on DSL. See also: http://distrowatch.com/weekly.php?issue=20090323#feature

**Comment by FabioLolix** [comment]
Tiny Core is already included, with the right start date
