### ISSUE TITLE
Add GoralixOS

### ISSUE THREAD

**Issue by krolmiki2011** [FabioLolix/LinuxTimeline#262]
Will be added **ONLY**  distributions that have a fullfilled page at the [info archive](https://distroware.gitlab.io/) 
and follow the [Timeline direction](https://github.com/FabioLolix/LinuxTimeline/issues/158)

The info archive code is both at:

* https://gitlab.com/Distroware/distroware.gitlab.io
* https://github.com/FabioLolix/distroware.gitlab.io

To know if I'm already aware of distrbutions please check if it is present [here](https://gitlab.com/Distroware/distroware.gitlab.io/-/tree/master/docs/os/Linux) or if an issue is open [here](https://github.com/FabioLolix/distroware.gitlab.io/issues)

* The timeline direction can be discussed here: [Timeline direction discussion](https://github.com/FabioLolix/LinuxTimeline/issues/157)

**Comment by FabioLolix** [comment]
Hi, at first glance don't seem that your distro have at least 2,5 years and put out at least 4 releases
