### ISSUE TITLE
Add distro: Splack Linux

### ISSUE THREAD

**Issue by fede2cr** [FabioLolix/LinuxTimeline#27]
* Distro name: Splack Linux

* Base distro: Slackware Linux

* Start date: 2001-Jul-14

* URL: https://github.com/fede2cr/splack_linux

* (optional) Description: Based on Slackware for Sparc processors

* Stop date: 2006-Aug-05
Mirror archive: https://ftp.sunet.se/mirror/archive/ftp.sunet.se/pub/Linux/distributions/splack/

**Comment by FabioLolix** [comment]
I'm sorry for taking so long, added with commit https://github.com/FabioLolix/LinuxTimeline/commit/51a2c1de24b37133e01214652fa0565351598f8d

Thanks for yours contibution, never heard of Splack Linux before, it is possible to try it with qemu?
