### ISSUE TITLE
RemixOS is discontinued

### ISSUE THREAD

**Issue by z3ntu** [FabioLolix/LinuxTimeline#29]
**Discontinuing a distro**

* Distro name: RemixOS

* Stop date: July 17, 2017

* Statement URL (if any): 
http://www.omgubuntu.co.uk/2017/07/remix-android-desktop-os-discontinued
https://www.facebook.com/remixglobal/posts/1909741975917394
http://www.androidpolice.com/2017/07/17/jide-technology-shifting-away-consumer-market-remix-os-discontinued/

**Comment by FabioLolix** [comment]
I'm sorry for taking so long, fixed with commit https://github.com/FabioLolix/LinuxTimeline/commit/67b4f231694780c22cd402cb30c66792d833611e

Thanks for yours contribution

I had read about it ine the news but hadn't time before
