### ISSUE TITLE
Request to add "Minimal Linux Live"

### ISSUE THREAD

**Issue by ivandavidov** [FabioLolix/LinuxTimeline#30]
* Distro name: Minimal Linux Live

* Base distro: None (compiled entirely from vanilla sources)

* Start date: 28-Jul-2014

* URL: http://minimal.linux-bg.org

* (optional) Color in hex: 0x6633FF

* (optional) Description: Minimal Linux Live is a tiny Linux distribution which is designed to be built from scratch using a collection of automated shell scripts. Minimal Linux Live offers a core environment with just the Linux kernel, GNU C library and BusyBox userland utilities. See also http://github.com/ivandavidov/minimal.

**Comment by FabioLolix** [comment]
Added with commit https://github.com/FabioLolix/LinuxTimeline/commit/397c921ec5ed3f4d67b29f45683edf31a640783b

Thanks for yours contribution
