### ISSUE TITLE
Add Swift Linux

### ISSUE THREAD

**Issue by jristz** [FabioLolix/LinuxTimeline#31]
**Adding a distro**

* Distro name: Swift Linux

* Base distro: Arch Linux

* Start date: 01 July 2006 - 01:01 (first public iso)

* URL: https://web.archive.org/web/20061108011223/http://shiftlinux.net:80/

* (optional) Color in hex: 006e92

* (optional) Description: Neowin's Shift Linux is designed to give the user an experience of being part of the Neowin community as well as having a simple, easy-to-use Live CD that can be installed to your hard drive, if you enjoy the way our distribution works. Shift is a free, GPL-based Linux distribution that can be freely distributed or modified. There are no restrictions with Shift.

* Stop date: 23 December 2007

* Statement URL (if any): The page went down and never go up again.

**Comment by FabioLolix** [comment]
Hello jristz, there is a bit of confusion here

Aside from distro name typo

* according to shiftlinux.net and Distrowatch Shift was based on Morphix/Debian and later Ubuntu.
I have seen it is listed in the Archwiki as last updated on 2009 but there are no further information.

* Why stop date on 2007-12-23 ?
 according to Distrowatch last version 0.6.5 was released on 2008-03-24

***

If it is lasted less than 2 years I'm unlikely to add it

**Comment by jristz** [comment]
The swift linux i use was based on the one in arch wiki and the date of
stop was the last snapshot that waybackmachine give without give me
problems.

I think maybe shiftlinux originally was going to be based on arch but that
ultimately dont happend OR there was a second swiftlinux, still a theory i
need to check.

**Comment by FabioLolix** [comment]
For reference,

* https://archive.fo/shiftlinux.net

* https://archive.fo/http://shiftlinux.net/news/item/shift-placed-on-indefinite-hold

Placed on hold on 8 May 2009

Started by Barney Tormey, Neowin admin

Simon Andrews, the Shift Linux project leader

Firefly is mentioned, which was based on Arch

> Anyone interested in developing a Linux distro should consider helping out Firefly Linux. It's a great project that spawned from Shift.

* https://distrowatch.com/table.php?distribution=firefly

An Arch conversion is mentioned

> thanks to CrimsonRedMk who did a kick ass job developing a majority of the developing and did an amazing job spearheading our Arch Linux conversion.

**Comment by FabioLolix** [comment]
Added as Morphix based https://github.com/FabioLolix/LinuxTimeline/commit/2e38d0c98551ba7c6acaf88e10259d55d555e995
