### ISSUE TITLE
Dragora lives

### ISSUE THREAD

**Issue by kelsoo** [FabioLolix/LinuxTimeline#33]
* Distro name:  Dragora GNU/Linux-Libre

http://www.dragora.org/

You have us down as dead!     Please check our timeline and or freenode dragora.    You will see we're very much alive and kicking .... Just slow moving  :-) The completely new release D3 is due out  ASAP.

http://dragora.org/repo.fsl/timeline
 irc://freenode/dragora

cheers  Kelsoo

**Comment by FabioLolix** [comment]
Fixed 88d36038e3acd39c9751bb2275479512829dfa3f

> You have us down as dead!

Sorry
