### ISSUE TITLE
dCore 

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#34]
**Template for adding/discontinuing a distro, all non optional fields are mandatory**

*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distro**

* Distro name:
dCore

* Base distro:
TinyCore

* Start date:
First announcement: October 2012 (I was not able to locate an apropriate posting in the forum)
alpha release: http://forum.tinycorelinux.net/index.php/topic,15612.html 
first release candidate: http://forum.tinycorelinux.net/index.php/topic,15799.html
first stable release: http://forum.tinycorelinux.net/index.php/topic,17870.0.html
* URL:
http://wiki.tinycorelinux.net/dcore:welcome

* (optional) Description:
dCore uses the same concept as Tiny Core, i.e. it runs completely from RAM, but dCore can utilize Debian/Ubuntu packages (.deb) and dCore can build its own extension format from their *.deb files.

So it is heavily influenced by Debian/Ubuntu. There are several flavours of dCore, which are based on the corresponding Debian/Ubuntu releases, for x86, see http://tinycorelinux.net/dCore/x86/release/ for an overview of architectures see: http://tinycorelinux.net/dCore/

**Comment by FabioLolix** [comment]
Fixed 03b19bd01d7b583fa04675048c26b0fb779c3405
