### ISSUE TITLE
aptosid looks dead

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#35]
**Template for adding/discontinuing a distro, all non optional fields are mandatory**

*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Discontinuing a distro**

* Distro name:
aptosid
* Stop date:
last Edition 5. May 2013
Status on distrowatch: inactive
not really much activity on their forum, see: 
      http://aptosid.com/index.php?name=PNphpBB2&file=viewtopic&t=2910

* Statement URL (if any):

**Comment by FabioLolix** [comment]
Fixed d1a1cae48ebaeb0486dd8f3680931ad5b87ed438
