### ISSUE TITLE
Add Backslash Linux

### ISSUE THREAD

**Issue by geremi1** [FabioLolix/LinuxTimeline#37]
* Distro name: Backslash Linux

* Base  Ubuntu (see release)

* Start date: 2 November 2016

* URL: https://en.m.wikipedia.org/wiki/BackSlash_Linux

* (optional) Description: see all information in the wiki page

All its update are on this wiki page.

**Comment by geremi1** [comment]
I don’t know what’s hex color.

**Comment by geremi1** [comment]
The new map don’t contain BackSlash Linux???

**Comment by FabioLolix** [comment]
I'll give a proper look in the next months, at first I'm not impressed by yet another Ubuntu derivate less than one year old but I've seen it is on distrowatch.

We have a different concept of "old"

**Comment by geremi1** [comment]
Ok, so it’ll be old in 5 days

**Comment by FabioLolix** [comment]
Development is paused, feel free to comment again when they resume
