### ISSUE TITLE
Can we make a version without EOL distros in it?

### ISSUE THREAD

**Issue by aaronfranke** [FabioLolix/LinuxTimeline#42]
I think it would be a good idea to make a version without EOL distros in it. 

There are a gigantic amount of distros on this list. Having every distro that ever existed on the list is useful for someone looking for a specific distro, or for anyone looking to see how many spin-offs of a distro were ever created, so the current version is good to have.

However, for people looking for an overview of current Linux distros and their families, having EOL distros on the list is just clutter. The list is absolutely **gigantic** right now. Simplifying the image to only include supported distros would be very nice.

I think this is only worth doing if it can be automated for each build. I would not expect you guys to maintain 2 branches, one with EOL distros removed, one not.

Thanks for considering.

**Comment by danhunsaker** [comment]
A bit of script-fu in `build.sh` should be able to generate `gldt-current.csv` and pass it through `gnuclad` as well. A PR to that effect would probably be welcome, I would imagine. 😊

**Comment by FabioLolix** [comment]
Hello @aaronfranke 

> There are a gigantic amount of distros on this list. Having every distro that ever existed

and I have already deleted distributions which had a lifespan of less then about 2 years :)

> having EOL distros on the list is just clutter
> I think this is only worth doing if it can be automated for each build

There is problem with deleting EOL distro,is that if they have parents the cladogram fail to generate, so this need to be considered

> Simplifying the image to only include supported distros would be very nice.

I'm not for this goal but not against it either, if someone can script these

> I would not expect you guys to maintain 2 branches

It was 99% or 98% me in the last year

**Comment by aaronfranke** [comment]
Keeping EOL distros who have in-life children is perfectly fine, that's probably the ideal solution.

I wish you guys good luck, I have no idea how to script this in. Not familiar with any of these tools.

**Comment by FabioLolix** [comment]
> I have no idea how to script this in.

Me too

**Comment by danhunsaker** [comment]
I'll see if I can take a crack at it sometime in the next couple of weeks.

**Comment by aaronfranke** [comment]
@danhunsaker How's it going?

**Comment by danhunsaker** [comment]
Haven't had a chance to sit down with it, still. It'll take some doing to do it right. Mostly, though, the script (probably in something more powerful than Bash) will need to load the CSV, build a dependency tree, then prune any leaves with an EOL entry until no more leaves have an EOL set. Any distros which have died, but spawned other distros at some point, will never be leaf nodes, so they'll never be pruned. 😊 The resulting list would then be pretty simple to use to filter the master CSV into a (temporary?) Current Distros CSV, and then pass that through the same conversion process as the master file to generate images for it.

**Comment by jorgenatz** [comment]
In the archive below is a shell script for removing the EOL distros (but not ones that non-EOL distros branch from), a csv of filtered data from the most recent version, and the resulting svg:
[No_EOL.tar.gz](https://github.com/FabioLolix/LinuxTimeline/files/2238411/No_EOL.tar.gz)

When building with gnuclad, errors will be emitted regarding connections. I was too lazy to build the functionality removing connections to deleted distros into the script.

**Comment by aaronfranke** [comment]
@jorgenatz Nice work! I could probably take your work and make a pull request, or you could.

Would we want this script to be integrated with `build.sh` or have it as a separate script, eg `build-active.sh`? In either case I'm thinking have it generate from the original CSV every time, and having the `.gitignore` ignore `gldt-active.csv`.

**Comment by jorgenatz** [comment]
Here is an archive with a tree that eliminates even more distros:
[Distrowatch_Active.tar.gz](https://github.com/FabioLolix/LinuxTimeline/files/2255790/Distrowatch_Active.tar.gz)

I based this off the criteria that they must be listed as Active in DistroWatch, as well as listed in the existing tree without an end date. However, it eliminates not only leaf nodes, but also parent nodes of active distributions. Hopefully it comes closer to an overview and is more easily digestible, although I do not have a script to automate the process.

**Comment by btreut** [comment]
@jorgenatz I successfully tried your script, but we have an additional dependency: it does not follow what I call "rebasing" (see e.g. issue #65), which means that a distribution was based on different and changed to another. These influences are reflected in dotted lines and the dotted line for SuSE ends at RedHat (this is an interesting surprise which presents some subtle irony).
Everything else: congratulations and applause.

**Comment by jorgenatz** [comment]
If you look very closely, you will see that that line to Jurix is actually two overlapping lines, one from SUSE to Jurix and another from SUSE to Red Hat. I see that they are certainly difficult to distinguish. Perhaps this may be considered an issue. Thank you for trying my script.

**Comment by btreut** [comment]
Hmm, I see, but I think that such influences should prevent the influencing distribution from being pruned.

**Comment by FabioLolix** [comment]
Time pass and I have changed my mind, I'll maintaining an additional timeline in which:

* discontinued distros will be removed
* freeware/remix/remasters and likely commarcial proprietary will be blacklisted
* will be a playground  for other changes, like I'm thinking of re-adding yocto/openembedded and derivates in different way
* I prefer to work alone on this one for a long while as I would like to match updates there with one on distroware (https://distroware.gitlab.io/) and don't burn out to keep up with stuff

https://github.com/FabioLolix/Opinionated-LinuxTimeline
