### ISSUE TITLE
Should GuixSD be shown as a descendent of NixOS?

### ISSUE THREAD

**Issue by therealpxc** [FabioLolix/LinuxTimeline#44]
While GuixSD now shares no components with NixOS, it was originally based on it in that it was inspired by it, created by a former NixOS developer, and even used the Nix daemon for queuing builds, and to this day uses a compatible format for derivations (artifacts in its build process). NixOS and GuixSD also form the closest thing there is to a family for functional package management-based GNU+Linux distros.

They certainly have more in common now than SUSE and Slackware, and arguably have a comparably connected history.

What do you think?

**Comment by FabioLolix** [comment]
It's interesting, really didn't know that

I'm thinking of using the connector '4' which is now used for merges, for use it for 'hard forks' also, for this and Chakra case, in which a distribution became really independent from another one

**Comment by therealpxc** [comment]
I think that would be good.

**Comment by FabioLolix** [comment]
Closing with commit 966dd92ab511f5a7f75a56698c1dbecb43995bd7
