### ISSUE TITLE
Add Artix Linux 

### ISSUE THREAD

**Issue by xnano200** [FabioLolix/LinuxTimeline#49]
**Adding a distribution**

* Name:Artix Linux 

* Base:Arch Linux

* Start date:2017-07-27

* URL:https://artixlinux.org/

* Color in hex:#66CCFF

* Description: see all information in the home page

**Comment by sbrl** [comment]
**Summary:** Artix is a sort-of fork of Manjaro OpenRC, which in itself is a configuration of regular Manjaro. It's also a sort-of fork of plain-old Arch too, which makes things rather confusing.

_(If I've got this wrong, please do let me know!)_

**Comment by konimex** [comment]
While Artix itself was a joint effort between Arch-OpenRC and Manjaro-OpenRC, however Artix is an Arch fork, not a Manjaro one.

**Comment by FabioLolix** [comment]
see #46

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/d9025408088e96f1e728b1746832fd5e5ddc0a30

**Comment by sbrl** [comment]
Cool, thanks @FabioLolix :smiley_cat:
