### ISSUE TITLE
One Link needs to be changed

### ISSUE THREAD

**Issue by sergds** [FabioLolix/LinuxTimeline#50]
One Link needs to be changed

Please change this **ftp://linorg.usp.br/sage/livecd/old/sagelive-readme.txt**
To this **http://linorg.usp.br/sage/livecd/old/sagelive-readme.txt**

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/fa857e647e36c28c796856cc4d4ba14f4eb06171
