### ISSUE TITLE
Add Q4OS

### ISSUE THREAD

**Issue by larkivisto** [FabioLolix/LinuxTimeline#51]
**Adding a distribution**

* Name: Q4OS

* Base: Debian

* Start date: July 2014

* URL: https://q4os.org/

* Description and history: Fork of Debian with the trinity desktop environment for low power systems and people who like old-school kde/windows. It has been around since 2014 and is currently 39th on distrowatch (https://distrowatch.com/table.php?distribution=q4os). Can't find much more info on it aside from linux youtuber reviews.

**Comment by FabioLolix** [comment]
Good, how can missed this?

I'm not sure about the starting date, they haven't started earlier?

I have contexted them, wating reply

**Comment by FabioLolix** [comment]
Got a reply some time ago with the precise date

Fixed https://github.com/FabioLolix/LinuxTimeline/commit/c5e713de2ceebfb02573c09f3fd8fc4c5d8bbd1e
