### ISSUE TITLE
Add Endless OS

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#52]
I am not sure what it means that endless OS is on the todo list of DISTRIBUTIONS.md, but maybe the information I am providing here makes the entry in the todo part obsolete :-)

**Adding a distribution**

* Name:  endless OS

* Base:  Debian (but heavily customized, see contributions on their [support pages](https://support.endlessm.com/hc/en-us/articles/115000097483-Why-can-t-I-use-apt-get-dpkg-dnf-or-rpm-commands-) and/or [forum](https://community.endlessos.com/t/apt-get-and-flatpak-how-to-download-and-install-from-e-g-github/6170/6)). 

* Start date: 18. July 2014 (first public release 2.1.0, see also the release history in their [forum](https://community.endlessos.com/t/what-about-a-release-history/5277/3)) 

* URL: https://endlessos.com/ and https://github.com/endlessm

* (optional) Description and history: talk about the project, for adding to distributions.md

Endless OS is not a typical Linux Distribution. It has a read only root file system, which is managed by OSTree.  EndlessOS uses flatpak as packet management system.
(extracted from Sec. "Endless OS" of the [developer information](https://endlessos.com/for-developers/))

**Comment by btreut** [comment]
maybe the detailed release history in their forum at https://community.endlessos.com/t/what-about-a-release-history/5277/3 helps. June 2015 would imply Vs. 2.3.3, which was according to https://github.com/endlessm/eos-desktop/releases?after=Release_2.4.2_debian a crtitical bug fix) . I guess that Vs. 2.0 released in June 11th, 2014 would be more adequate.

**Comment by FabioLolix** [comment]
Thanks for the link, even better of what I hoped

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/af7065e979209b078c27a9981ef6a8b41b94b063

**Comment by btreut** [comment]
Dear Fabio,

yes, I was also very suprised about the provided details. Thanks for including it.
--
   Bernhard
