### ISSUE TITLE
Incorrect starting date for Void Linux

### ISSUE THREAD

**Issue by Aleppi** [FabioLolix/LinuxTimeline#54]
According to [this](https://wiki.voidlinux.eu/Void_Linux) page Void Linux started in 2008, not in the middle of 2015 as the timeline states at the moment. Unless there is some information I do not know of, the timeline's starting date is incorrect. Please change the starting year to 2008.

**Comment by FabioLolix** [comment]
Fixed https://github.com/FabioLolix/LinuxTimeline/commit/4deb3f95e7bbc6fed8b4b9613126a64ac3827477
