### ISSUE TITLE
Add januslinux

### ISSUE THREAD

**Issue by protonesso** [FabioLolix/LinuxTimeline#57]
* Name: januslinux

* Base: Independent

* Start date: 26th May 2017

* URL: https://januslinux.github.io

* Color in hex: #ff00bf

* Description and history: Fast and mini Linux distribution uses musl libc and busybox userland tools

**Comment by protonesso** [comment]
Release date: 27th November 2017

**Comment by FabioLolix** [comment]
I know isn't written anywhere but I will not accept distributions that are in beta/alpha/early stage anymore

Will add in the future

**Comment by protonesso** [comment]
Thanks for information

**Comment by protonesso** [comment]
januslinux have no "releases" anymore. Now I will compile monthly releases like "2018.08".

**Comment by FabioLolix** [comment]
Ok

**Comment by protonesso** [comment]
januslinux is discontinued

**Comment by protonesso** [comment]
no it live again

**Comment by protonesso** [comment]
It's not I'm development anymore
