### ISSUE TITLE
Add: Red Star OS

### ISSUE THREAD

**Issue by MagicLizard** [FabioLolix/LinuxTimeline#58]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name: Red Star OS

* Base: Fedora

* Start date: 2008

* (eventual) Name changes with date: 

* URL: https://en.wikipedia.org/wiki/Red_Star_OS

* (optional) Color in hex: f42427

* (optional) Description and history: North Koreas linux distrbution.

**Comment by FabioLolix** [comment]
I have no interest in adding state-sponsored control systems

Also with lack of information, real URL (maybe is not visible from outside North Korea)? Last version is from 2014

**Comment by nicolasmaia** [comment]
I think this is relevant to have (it's certainly notable), and adding it in no way means endorsement of North Korea.

Also, Nova, the Cuban state-sponsored distro, is already in this timeline.

Some older distros don't have URLs either, or they do but they're offline and no copy on the Wayback Machine exists.

**Comment by xingjiapeng** [comment]
Some infomations:
https://namu.wiki/w/%EB%B6%89%EC%9D%80%EB%B3%84
It seems this OS is started to be developed in 2001

**Comment by FabioLolix** [comment]
> Also, Nova, the Cuban state-sponsored distro, is already in this timeline.

Does Nova fingerprint its users?

> adding it in no way means endorsement of North Korea.

Sure, it is not an endorsement. the direction I want to take for the timeline is the one of quality distros and Red Star is not there

> I think this is relevant to have (it's certainly notable)

I don't find it notable but peculiar; and in a negative way.
Let's be honest Red Star outside of North Korea is almost vapoware, now the big question: would you like to use it as your primary or secondary system?

> Some older distros don't have URLs either, or they do but they're offline and no copy on the Wayback Machine exists.

This is one of the reason I'm creating a new info archive at:

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/

Informations about *any* distro is welcome

**Comment by nicolasmaia** [comment]
I understand that you don't like this distro (neither do I), but the point is to document the history of distros, no?

**Comment by FabioLolix** [comment]
> but the point is to document the history of distros, no?

I have setted relues and guidelines for having distro that provide some quality

However I have thinked about making also a "full edition" with 'everything', given that there is a fullfiled enough page at https://fabiololix.gitlab.io/
