### ISSUE TITLE
piCorePlayer: new URL: https://www.picoreplayer.org

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#63]
* Name: piCorePlayer

* URL: moved from: https://site.google.com/site/picoreplayer/home
          to: https://www.picoreplayer.org

regards, Bernhard

**Comment by FabioLolix** [comment]
Great, had seen that too some days ago while playing with piCorePlayer then even forgot to take note

**Comment by FabioLolix** [comment]
Corrected, thanks https://github.com/FabioLolix/LinuxTimeline/commit/62fbd8aa271b4d3d1aca13e63ccfd54a9507e722
