### ISSUE TITLE
The "new SUSE distribution" (SuSE 4.2 - April 1996) is not based on Slackware

### ISSUE THREAD

**Issue by xosevp** [FabioLolix/LinuxTimeline#65]
Earliest “SUSE Linux distributions” were originally ONLY a German translation of Slackware.

For building its *very own distribution* of Linux, SUSE used the Jurix distribution as a fresh start point. And heavily influenced by Red Hat Linux.

For more info:
- https://en.opensuse.org/Archive:S.u.S.E._Linux_4.2
- http://linux.mathematik.tu-darmstadt.de/pub/linux/distributions/jurix/docs/history.html
- http://en.wikipedia.org/wiki/Jurix
- http://en.wikipedia.org/wiki/SuSE_Linux#Origins

**Comment by btreut** [comment]
yes, but as far as I understand the logic of the timeline, rebasing a distribution is reflected by dotted lines between the influencing and the influenced distribution. Rebasing does not change the branch, where the influenced distribution is located. To my understanding this keeps the trees manageable despite it is sometimes misleading (as for SuSE).

**Comment by FabioLolix** [comment]
as @btreut said, it is even worse when it is gone independent since there are no connectors at all

**Comment by FabioLolix** [comment]
Done d6b6c95a2102915d0149b7668c721faa1cf2e1d2
