### ISSUE TITLE
Wrong foundation dates

### ISSUE THREAD

**Issue by xosevp** [FabioLolix/LinuxTimeline#67]
Foundation dates should be revised, at least for the first distributions.
And establish a common base, based on one of these criterion:
- Project/company foundation.
- Starting to work in the distribution.
- First public(alpha/beta) distribution.
- First stable distribution.

Red Hat and Debian are clear examples of wrong dates:
https://en.wikipedia.org/wiki/Red_Hat#History
https://en.wikipedia.org/wiki/Red_Hat_Linux#Version_history
https://en.wikipedia.org/wiki/Debian#History
https://en.wikipedia.org/wiki/Debian_version_history#Release_table

**Comment by FabioLolix** [comment]
> Project/company foundation.

I don't care about company foundation, I care about public available code if exist and public releases

>     Starting to work in the distribution.
>     First public(alpha/beta) distribution.
>     First stable distribution.
> 
> Red Hat and Debian are clear examples of wrong dates:

You can report here what you would use and why

**Comment by xosevp** [comment]
You can extract the info from:

Debian:
- https://www.ibiblio.org/pub/historic-linux/distributions/debian-0.91/ChangeLog
- https://www.debian.org/doc/manuals/project-history/detailed.en.html
- https://en.wikipedia.org/wiki/Debian_version_history

Red Hat Linux:
- https://en.wikipedia.org/wiki/Red_Hat_Linux#Version_history
