### ISSUE TITLE
home of Deepin moved

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#68]
home of deepin moved apparently from http://linux.deepin.org to http://www.deepin.org/ and that page redirects to https://www.deepin.org/en/

**Comment by FabioLolix** [comment]
Fixed, thanks 
https://github.com/FabioLolix/LinuxTimeline/commit/58afcbd02f9bc0c4691fe231aac3f057bda52059 https://github.com/FabioLolix/LinuxTimeline/commit/40afec088fc185da21851500f9c6a3fe3c71b888

Used https://www.deepin.org/, to me redirects to https://www.deepin.org/it/ for example
