### ISSUE TITLE
Invalid ID's in the SVG

### ISSUE THREAD

**Issue by RazrFalcon** [FabioLolix/LinuxTimeline#69]
`__stop_Descent|OS`, `__fadeout_Slack/390`, etc. are not valid SVG/XML ID's. See a [validator output](https://validator.w3.org/check?uri=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F1%2F1b%2FLinux_Distribution_Timeline.svg&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices).

[Allowed characters.](https://www.w3.org/TR/xml/#NT-NameStartChar)

**Comment by FabioLolix** [comment]
How can I improve the thing in practice?

**Comment by RazrFalcon** [comment]
Prefer `[A-Za-z0-9_]` names, where the first character is no a number.

**Comment by FabioLolix** [comment]
That is how distribution are called but will take a look to avoid that errors, I guess I'll replace `|` and with `/` with spaces, etc..

**Comment by FabioLolix** [comment]
There are still a warning and an error

* Warning
  > Line 2874, Column 81: This validator does not validate Inkscape extensions properly. Inkscape-specific errors may go unnoticed.
… inkscape:label='Background' inkscape:groupmode='layer' id='layer_background' >

* Error
  > Line 8853, Column 26: Bad value connector legend for attribute id on SVG element g: Not a valid XML 1.0 name.
 <g id="connector legend">

the error can be cleaned with your svgcleaner

**Comment by RazrFalcon** [comment]
Could you show a line with this error?

**Comment by FabioLolix** [comment]
Here it is, lost it in copy-pasting before, 
* \<g id="connector legend">

Is the same you can see in the validator output, the last one

**Comment by RazrFalcon** [comment]
Yes. Spaces are forbidden.

**Comment by FabioLolix** [comment]
Removed the space manually, it is left only the warning now
