### ISSUE TITLE
New Relase ?

### ISSUE THREAD

**Issue by btreut** [FabioLolix/LinuxTimeline#71]
[...]
Next release will be out in September!
Hopefully future release will not be so distant, let's say not more than 3 months each.
If you have some request or tips it's time now :)
[...]
_Originally posted by @FabioLolix in https://github.com/FabioLolix/LinuxTimeline/issues/28#issuecomment-320941467_

Last release is 17.10, that is 15 month ago, what about a new one?

**Comment by FabioLolix** [comment]
New one at the end of April (26 or 27)

Next one on the Linux Day or the day before
***
> Hopefully future release will not be so distant, let's say not more than 3 months each.

Completely changed my mind about that, will made 1 or 2 release a year.

There will be more work on the readme then on gldt.csv I guess

**Comment by btreut** [comment]
> 

> 
> 
> New one at the end of April (26 or 27)
> 
> Next one on the Linux Day or the day before
> 
> > Hopefully future release will not be so distant, let's say not more than 3 months each.
> 
> Completely changed my mind about that, will made 1 or 2 release a year.
> 
> There will be more work on the readme then on gldt.csv I guess

thanks in advance.

**Comment by FabioLolix** [comment]
I'll close the issue when the new relese is out :)

**Comment by nee-san** [comment]
@FabioLolix you haven't maintained it for months

**Comment by FabioLolix** [comment]
Release will be tomorrow

**Comment by btreut** [comment]
Magnifico

**Comment by FabioLolix** [comment]
Still working on it, tagging will probably be after midnight (local time)

**Comment by FabioLolix** [comment]
Released ce9b04805fce5b343a7d60ce9435e652aeb40ec0

https://github.com/FabioLolix/LinuxTimeline/releases/tag/v19.04
