### ISSUE TITLE
missing distro: CAELinux

### ISSUE THREAD

**Issue by alosslessdev** [FabioLolix/LinuxTimeline#72]
* Name: CAELinux

* Base: Xubuntu

* Start date: 2005

* (eventual) Name changes with date: none

* URL: https://caelinux.com/CMS3/

* (optional) Color in hex:

* (optional) Description and history: A linux distro, like kali linux but with computer assisted engineering software preinstalled, instead of penetration testing software.

**Comment by FabioLolix** [comment]
Added in the waiting list since it is created with remixing tools (pinguybuilder) and is quite discontinous, CAELinux 2018 has been released on 04 January 2019 and is based on Xubuntu 16.04 LTS while Xubuntu 18.04 LTS has been out since a while

7a625e2eedc0af847f0f1275038ce43d1f64a746

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
