### ISSUE TITLE
Discontinuation of Antergos.

### ISSUE THREAD

**Issue by pushkar-bharambe** [FabioLolix/LinuxTimeline#79]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:

* Base:

* Start date:

* (eventual) Name changes with date: 

* URL:

* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md

**Discontinuing a distribution**

* Name: Antergos

* Stop date: 21/05/2019

* Statement URL (if any): https://antergos.com/blog/antergos-linux-project-ends/

**Comment by FabioLolix** [comment]
PR #80 has been merged
