### ISSUE TITLE
SystemRescueCD is now Arch-based

### ISSUE THREAD

**Issue by inkeso** [FabioLolix/LinuxTimeline#81]
since version 6.0.0 (2019-02-02) SystemRescueCD is no longer based on Gentoo but on ArchLinux, see http://www.system-rescue-cd.org/Changes-x86/

**Comment by FabioLolix** [comment]
Hello @inkeso, thanks for your patience, I had read about it in the news but didn't know how I cloud switch base for the distros at that time

Done ed4313cc192fb5e8345ee6053d20c338b374de10
