### ISSUE TITLE
Missing Icons for major distros

### ISSUE THREAD

**Issue by JoshuaKimsey** [FabioLolix/LinuxTimeline#82]
I was curious about something. I was watching [this video on Linux distros](https://youtu.be/DKFnqAtEOvc) from late 2018 and he showed an image of the Linux Timeline from here. However, the version he showed has several icons not currently found in the version here on GitHub, such as for Ubuntu, Fedora, Suse, Gentoo, Arch, and more. Is this a custom version he made or was this a previous feature set no longer offered? It makes sense to include these icons, as it is what people most relate to those distros.

If some of the icons for other highly popular distros could be added, I think it would really add to the graphical appeal of the Timeline!

**Comment by FabioLolix** [comment]
> the version he showed has several icons not currently found in the version here on GitHub, such as for Ubuntu, Fedora, Suse, Gentoo, Arch, and more. Is this a custom version he made or was this a previous feature set no longer offered?

It is a custom version

For each icon, which is needed in .SVG, need to be tracked license and copyright

Icons also need to be resized and some don't work well or at all with gnuclad

**Comment by FabioLolix** [comment]
See #153
