### ISSUE TITLE
add /e/ (formerly Eelo)

### ISSUE THREAD

**Issue by RasheedAZ** [FabioLolix/LinuxTimeline#89]
**Adding a distribution**

* Name: /e/

* Base:  LineageOS, a fork of the CyanogenMod and Android 

* Start date: September 2018

* (eventual) Name changes with date: 

* URL: https://e.foundation

* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md

**Comment by FabioLolix** [comment]
Hello @RasheedAZ and thank you for your patience

I'm following news about /e/OS since its inception and I'm very interested about it.

Futher addition to the timeline will be for projects that are at least 2.5 year old, are of quality and have a fullfilled page at my new open archive

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/

**Comment by FabioLolix** [comment]
The project was known as Eelo for a while but need to find the precise date

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template

**Comment by tuxayo** [comment]
How does info archive works? Because the example are broken.
Should /e/ be requested to be added there instead?

**Comment by FabioLolix** [comment]
> How does info archive works? 

It is a static website build with python-mkdocs from markdown files, it is hosted on GitLab pages

> the example are broken

Some things have been moved around, now Linux have a capital letter and new home is here https://distroware.gitlab.io

https://distroware.gitlab.io/os/Linux/0-9/4m/

https://distroware.gitlab.io/os/Linux/t/t2/

Very recently I've made a page with basic instructions for filling pages https://distroware.gitlab.io/contributing/fullfilling/

>  Should /e/ be requested to be added there instead?

In practice I don't do requests, if you want something to be added help provide informations, the page for /e/ was missing and I've created it (blank) now
