### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by lowlevelm** [FabioLolix/LinuxTimeline#90]
The last commit was 8 months ago. Is this project still maintained?

**Comment by FabioLolix** [comment]
Hello, I'm still alive and with several ideas for the timeline and the lists

If you have any bug reports or a suggestion for a very well done distro you're welcome

**Comment by SouthernWolf95** [comment]
Fantastic!!! I’d actually just forked the project yesterday to start making updates for 2020, but knowing your still active is wonderful! I’ll get all the changes and updates I’d planned written up in a separate issue here shortly! If you like the changes I can make a pull request to. :)
