### ISSUE TITLE
Red Flag Linux is not over now

### ISSUE THREAD

**Issue by xingjiapeng** [FabioLolix/LinuxTimeline#93]
Red Flag Linux is not over now, it returned on 2018-04-03
but it doesn't develop personal desktop, it is only focus on enterprise.
[红旗软件-国产基础软硬件综合服务提供商](http://www.redflag-linux.com/)

**Comment by xingjiapeng** [comment]
http://www.chinaredflag.cn/

**Comment by FabioLolix** [comment]
Merged the commit
