### ISSUE TITLE
add NeoKylin

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#94]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
NeoKylin or 中标麒麟
* Base:
NeoKylin's package manager is rpm, it is based on RHEL.
* Start date:
1999.11，中软Linux 1.0 (Cosix Linux 1.0)
2004.02，中标普华1.0 (NeoShine)
2010.12.16，中标麒麟 (NeoKylin)
* (eventual) Name changes with date: 
中软Linux(Cosix Linux) became 中标普华Linux([NeoShine](https://distrowatch.com/table.php?distribution=neoshine)) in 2003,
中标普华Linux and [NUDT](https://www.nudt.edu.cn/)'s Kylin OS merge to NeoKylin on 2010.12.16,
* URL:
http://www.cs2c.com.cn/
* (optional) Color in hex:
B60009
* (optional) Description and history: talk about the project, for adding to distributions.md
more infomation:
I tried to find more info in the Internet about NeoKylin:
[NeoShine on distrowatch](https://distrowatch.com/table.php?distribution=Neoshine)
《电子测试》1999年11期 : 
[COSIX Linux中文化、更安全的Linux操作系统(cnki)](https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFD9899&filename=WDZC199911013&v=MDY3NjdmWStadUZpN2dWN3ZBTWluUmJiS3hGOWpOcm85RVo0UjhlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSN3E=)
[ COSIX Linux中文化、更安全的Linux操作系统(iData)](https://search.cn-ki.net/doc_detail?dbcode=CJFD&filename=WDZC199911013&df=0FjWXV0a0ZlMmFWZopnTtdUe1RGeWR0YDJ2azVkV3IjSKJVMoZFTFN2TyZkTvEHZVpkbJdVZXJUdmRUaYZUROJnYLVnZ4p1SExENqRjRONjNS1mWR9WSvQ3Qz1mUuFzcCl1UIJHTWZGaKp1LZJEe1J1Z2VWUxAXR)  ( [I have downloaded it.](https://share.weiyun.com/59jexrs) )
[ COSIX Linux1.0(cnki)](https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFD9899&filename=WDZC199911072&v=MjYwODU3cWZZK1p1Rmk3Z1ZicklNaW5SYmJLeEY5ak5ybzlDWm9SOGVYMUx1eFlTN0RoMVQzcVRyV00xRnJDVVI=) ([I have downloaded it.](https://share.weiyun.com/5lOEnWG))
http://linux.kutx.cn/linux/linux6365.htm
http://www.cs2c.com.cn/index.php?id=109
https://baike.baidu.com/item/%E4%B8%AD%E6%A0%87%E9%BA%92%E9%BA%9F
https://bbs.deepin.org/forum.php?mod=viewthread&tid=156886&extra=
it is only focus on enterprise

**Comment by xingjiapeng** [comment]
**Brea New:** Kylin OS and NeoKylin merge in Tianjin
http://www.kylinos.cn/news_show.aspx?id=3357
http://www.cs2c.com.cn/news/index.php?id=1375

**Comment by xingjiapeng** [comment]
[Kylin OS](http://www.kylinos.cn/) (based on Red Hat, too) is developed by the same company/organization with [Ubuntu Kylin](http://www.ubuntukylin.com/).
Since Kylin OS and NeoKylin merge in Tianjin, they are develop by the same company, called Kylinsoft.
[天津麒麟正式更名为麒麟软件 国产操作系统主力军吹响出征号角！ - 公司新闻 - 麒麟软件有限公司](http://www.kylinos.cn/news_show.aspx?id=3176)

**Comment by xingjiapeng** [comment]
Kylin OS is based on FreeBSD at first(how to solve this???)(2006 winter), and then it based on RHEL after V3.0(2009)

**Comment by FabioLolix** [comment]
> Kylin OS is based on FreeBSD at first(how to solve this???)(2006 winter), and then it based on RHEL after V3.0(2009)
We'll eventually add it at v3.0 and mention it was initially based on FreeBSD in Readme.md

Thanks for you interest in the timelines

This week I should be able to expose my vision about the timeline and in which directions proceed

**Comment by xingjiapeng** [comment]
here is a picture can show the history clearly, come from [The 15th Open Source China Open Source World Summit](http://copu.softic.com.cn/):
![](https://img.vim-cn.com/e5/7746a6a525f14675a705b62c6f4a74ad840a59.png)

**Comment by FabioLolix** [comment]
Futher addition to the timeline will be for projects that are at least 2.5 year old, are of quality and have a fullfilled page at my new open archive

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
