### ISSUE TITLE
add Emind

### ISSUE THREAD

**Issue by xingjiapeng** [FabioLolix/LinuxTimeline#95]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
一铭操作系统 (Emind)
* Base:
Debian, maybe, i'm not sure...
* Start date:
The company was founded in 2004...
* (eventual) Name changes with date: 

* URL:
[一铭操作系统-一铭软件股份有限公司](https://www.emindsoft.com.cn/)
* (optional) Color in hex:
171662
* (optional) Description and history: talk about the project, for adding to distributions.md
https://www.emindsoft.com.cn/index.php?s=/Company
https://www.emindsoft.com.cn/product/os-desktop
https://www.emindsoft.com.cn/product/os-server

**Comment by FabioLolix** [comment]
Futher addition to the timeline will be for projects that are at least 2.5 year old, are of quality and have a fullfilled page at my new open archive

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/



> Base:
> Debian, maybe, i'm not sure...
> 
> Start date:
> The company was founded in 2004...

Not much infos

By the way I know only Italian and English

**Comment by xingjiapeng** [comment]
cannot make sure it is really opensource. close.
