### ISSUE TITLE
add Magic Linux

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#96]
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:
Magic Linux
* Base:
Fedora
* Start date:
2003-01-04
* (eventual) Name changes with date: 

* URL:
https://www.linuxfans.org/magic-linux
http://www.magiclinux.org/
* (optional) Color in hex:
3793DB
* (optional) Description and history: talk about the project, for adding to distributions.md
http://www.magiclinux.org/
It is back, at last.

**Comment by FabioLolix** [comment]
Futher addition to the timeline will be for projects that are at least 2.5 year old, are of quality and have a fullfilled page at my new open archive

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/

> Magic Linux 4.0.0 机构知识库虚拟化平台版发行公告
> 星期六, 05/26/2018

It is more then 2 years from the last release

**Comment by FabioLolix** [comment]
Rules for inclusion have changed, new additions need to already have a sufficiently full-filled page [at the info archive](https://fabiololix.gitlab.io/)

Rules: https://github.com/FabioLolix/LinuxTimeline/issues/158

 * https://github.com/FabioLolix/fabiololix.gitlab.io
 * https://gitlab.com/FabioLolix/fabiololix.gitlab.io
 * https://fabiololix.gitlab.io/

Some pages examples: 
* https://fabiololix.gitlab.io/os/linux/b/bbqlinux/
* https://fabiololix.gitlab.io/os/linux/a/almalinux/
* refer to template.txt in gitlab.io main folder for up to date template
