### ISSUE TITLE
Pop OS should be Pop!_OS

### ISSUE THREAD

**Issue by xingjiapeng** [FabioLolix/LinuxTimeline#98]
Pop OS should be Pop!_OS
https://system76.com/pop
https://distrowatch.com/table.php?distribution=popos

**Comment by FabioLolix** [comment]
I know but see issue #69

**Comment by xingjiapeng** [comment]
Sorry, and thanks.

**Comment by xingjiapeng** [comment]
sorry, I can't understand that.
I tried to add the special characters in source, build and open svg with inkscape but it works good.
![](https://img.vim-cn.com/e8/07dd781e9d30082f2bee9c222037d419d3595b.png)
![](https://img.vim-cn.com/65/3fd6786f0b01dca64e7db879fefc982bef28ab.png)
output:  
```
gnuclad HEAD: gldt.csv => gldt.svg
Computing cladogram for 571 nodes, 126 connectors and 6 domains...
Done
```
Thanks.

**Comment by xingjiapeng** [comment]
there is a distro called Ångström in 
https://github.com/FabioLolix/LinuxTimeline/blob/5993819acfa513abdd31dc77f362ac6f5af1a1ea/ldt.csv#L658
